version: '3.8'
services:
  jenkins:
    restart: always
    image: jenkins/jenkins:lts-jdk11
    privileged: true
    user: root
    ports:
      - 8081:8080
      - 50000:50000
    container_name: jenkins
    labels:
      - version 1.0.1
    volumes:
      - ~/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
  